# PlantUML Editor

1. select template
2. write uml diagram

Preview is Ctrl-Enter or Cmd-Enter

@startuml

left to right direction

actor User

User --> (1. select template)
User --> (2. write uml diagram)

legend center
  Preview is Ctrl-Enter or Cmd-Enter
endlegend

@enduml